<a href="https://colab.research.google.com/github/shahjamanbadhon/Deep-Learning/blob/main/Activation_Functions_in_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# !pip install numpy

In [4]:
import numpy as np

# 1. ReLU - Rectified Linear Unit (Hidden Layer)

In [5]:
def relu(x):
    return np.maximum(0, x)


In [6]:
relu(10)

np.int64(10)

In [7]:
relu(-10)

np.int64(0)

In [8]:
relu(np.array([-1, 0, 1, 2]))

array([0, 0, 1, 2])

# 2. Leaky ReLU (Hidden Layer)

Leaky ReLU allows a small, positive gradient when the unit is not active.

In [9]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, x * alpha)


In [10]:
leaky_relu(-1)

array(-0.01)

In [11]:
leaky_relu(np.array([-1, 0, 1, 2]))

array([-0.01,  0.  ,  1.  ,  2.  ])

# 3. ELU - Exponential Linear Unit (Hidden Layer)

ELU has a small slope for negative values, unlike ReLU, to avoid the dying ReLU problem.

In [12]:
def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [13]:
elu(5)

array(5.)

In [14]:
elu(np.array([-1, 0, 1, 2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

# 4. Sigmoid (Output Layer & Binaryclass Problem)

In [15]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [16]:
sigmoid(np.array([-1, 0, 1, 2]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

# 5. Softmax (Output Layer & Multiclass Problem)

Softmax converts a real vector to a vector of categorical probabilities.

In [17]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)


In [18]:
proba = softmax(np.array([-1, 0, 1, 2]))
proba

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [19]:
sum(proba)

np.float64(1.0)

# 6. Swish (Hidden Layer)

Swish is a self-gated activation function.

In [20]:
def swish(x, beta=1.0):
    return x * sigmoid(beta * x)


In [21]:
swish(5)

np.float64(4.966535745378576)

In [22]:
swish(np.array([-1, 0, 1, 2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

# 7. Linear (Output Layer)

Linear or identity activation function returns the input directly.

In [23]:
def linear(x):
    return x

In [24]:
linear(10)

10

# 8. Tanh (Hyperbolic Tangent)

In [25]:
def tanh(x):
    return np.tanh(x)

In [26]:
tanh(10)

np.float64(0.9999999958776927)

In [27]:
tanh([-1, 0, 1, 2])

array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

In [28]:
import math

In [29]:
def tanh(x):
    result = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
    return result

In [30]:
tanh(-1)

-0.7615941559557649